import { createStore } from "solid-js/store";

export const get_default_data = () => {
  return {
    "full name": "",
    designation: "",
    phone: "",
    address: "",
    "email address": "",
    "github username": "",
    profile: "",

    education: [
      { institution: "", qualification: "", time: "" },
    ],

    "work experience": [
      { company: "", position: "", time: "" },
    ],

    skills: [""],
    interests: [""],
    oss: [{ "project name": "", description: "", languages: "" }],
  };
};

export const get_demo_data = () => {
  return {
    "full name": "Chirayu Maru",
    designation: "Frontend web developer",
    phone: "+91 8824976872",
    "email address": "chirayumaru@gmail.com",
    "github username": "chirayu2107",
    profile:
      "I'm a Frontend Web developer and an open source & linux enthusiast. I use Gnu / Artix linux and I maintain several open source projects at github. I'm looking forward to get a junior frontend web developer's position at a reputed corporation / startup and building user friendly & responsive interfaces with Reactjs.",

    education: [
      {
        institution: "Vellore Institute of Technology",
        qualification: "Bachelor of Technology in CSE",
        time: "2021-2025",
      },
      {
        institution: "Birla Shiksha Kendra, Chittorgarh",
        qualification: "intermediate (11-12th grade)",
        time: "2019-2021",
      },
      {
        institution: "Birla Shiksha Kendra, Chittorgarh",
        qualification: "10th grade (SSC)",
        time: "2019",
      },
    ],

    "work experience": [
      {
        company: "Gifting Memories",
        position: "Web Developer Intern",
        time: "2023 Aug - 2023 Nov",
      },
    ],

    skills: [
      "html skill-icons:html",
      "css skill-icons:css",
      "javascript skill-icons:javascript",
      "typescript skill-icons:typescript",
      "react logos:react",
      "tailwind css logos:tailwindcss-icon",
      "java logos:java",
      "python logos:python",
      "aws logos:aws"
    ],

    oss: [
      {
        "project name": "B2B E-Commerce Website ",
        description:
          "Developed an online platform specifically designed for transactions between businesses",
        languages: "React.Js, Tailwind CSS, Node.Js, Firebase ",
      },
      {
        "project name": "Resukraft",
        description:
          "Resukraft for making beautiful resumes & supports exporting to high quality svgs & pdfs. This resume is generated by resukraft web app.",
        languages: "typescript, solidJs, unocss, vite",
      },
      {
        "project name": "ImagiGen",
        description:
          "A globally accessible application that takes user prompts and generates solutions in real-time.",
        languages: "HTML, CSS, JavaScript ",
      },
    ],
  };
};

export const [store, setStore] = createStore(get_default_data());
